---

- name: tranform sql setup template
  template:
    dest: /tmp/sql.sh
    src: sql.sh.j2
    mode: 0555



- name: execute sql setup
  shell: /tmp/sql.sh
  notify: 
    - clean-up sql.sh

- name: modify mysql.conf to allow access to web server
